export const ACTION_EXAMPLE_ONE = 'ACTION_EXAMPLE_ONE'
export const ACTION_EXAMPLE_TWO = 'ACTION_EXAMPLE_TWO'
export const MUTATION_EXAMPLE_ONE = ' MUTATION_EXAMPLE_ONE'
export const MUTATION_EXAMPLE_TWO = ' MUTATION_EXAMPLE_TWO'

export default {
  ACTION_EXAMPLE_ONE,
  ACTION_EXAMPLE_TWO,
  MUTATION_EXAMPLE_ONE,
  MUTATION_EXAMPLE_TWO,
}